-- ============================================================================
-- 0001_lookups.sql — reference vocabularies + season/provenance spine
-- ----------------------------------------------------------------------------
-- Controlled vocabularies are lookup tables (NOT Postgres ENUM) so they port to
-- Oracle verbatim and serialize to JSON without joins. Seed data is loaded by
-- src/db/seed.ts (portable idempotent inserts), keeping these files pure DDL for
-- the FWP DBA review + Oracle port.
-- oracle-note: identity columns are 12c+ verbatim; VARCHAR → VARCHAR2; SMALLINT
--   booleans → NUMBER(1); TIMESTAMP WITH TIME ZONE exists.
-- ============================================================================

-- Up Migration

-- Season year — the business time axis. 2025 = license year Mar 1 2025–Feb 28 2026.
CREATE TABLE regs.season_year (
  season_year   SMALLINT PRIMARY KEY,
  starts_on     DATE NOT NULL,
  ends_on       DATE NOT NULL,
  adopted_on    DATE,
  status_code   VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
                CHECK (status_code IN ('DRAFT','PUBLISHED','ARCHIVED')),
  notes         VARCHAR(2000)
);

-- Source document (a PDF book) — provenance root.
CREATE TABLE regs.source_document (
  source_doc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year   SMALLINT NOT NULL REFERENCES regs.season_year,
  doc_code      VARCHAR(60) NOT NULL,
  title         VARCHAR(200) NOT NULL,
  file_name     VARCHAR(200),
  adopted_on    DATE,
  valid_from    DATE,
  valid_to      DATE,
  source_url    VARCHAR(1000),
  CONSTRAINT uq_source_doc UNIQUE (season_year, doc_code)
);

-- FWP administrative region 1–7.
CREATE TABLE regs.region (
  region_id     SMALLINT PRIMARY KEY CHECK (region_id BETWEEN 1 AND 7),
  region_name   VARCHAR(60) NOT NULL
);

-- District geography: which ArcGIS layer keys a code. Deer/elk share HD; antelope separate.
CREATE TABLE regs.geography (
  geography_code  VARCHAR(20) PRIMARY KEY,
  display_name    VARCHAR(60) NOT NULL,
  arcgis_layer_id SMALLINT,
  arcgis_key_fld  VARCHAR(30) DEFAULT 'DISTRICT',
  app_geo_type    VARCHAR(20)
);

-- Species handled by this DB (deer/elk/antelope in v1).
CREATE TABLE regs.species (
  species_code    VARCHAR(20) PRIMARY KEY,
  display_name    VARCHAR(60) NOT NULL,
  geography_code  VARCHAR(20) NOT NULL REFERENCES regs.geography
);

-- Instrument type taxonomy.
CREATE TABLE regs.instrument_type (
  instr_type_code VARCHAR(20) PRIMARY KEY,
  display_name    VARCHAR(60) NOT NULL,
  is_draw_default SMALLINT NOT NULL CHECK (is_draw_default IN (0,1))
);

-- Named season-window column (Early/Archery/General/Heritage ML/Late/Season).
CREATE TABLE regs.season_type (
  season_type_code VARCHAR(20) PRIMARY KEY,
  display_name     VARCHAR(60) NOT NULL,
  weapon_label     VARCHAR(40) NOT NULL,
  sort_order       SMALLINT NOT NULL DEFAULT 0
);

-- Structured restriction vocabulary.
CREATE TABLE regs.restriction_type (
  restr_code    VARCHAR(30) PRIMARY KEY,
  category      VARCHAR(20) NOT NULL CHECK (category IN
                ('LAND_CLASS','EQUIPMENT','ELIGIBILITY','PURCHASE','GEO_LIMIT','BAG','OTHER')),
  display_name  VARCHAR(120) NOT NULL,
  needs_value   SMALLINT NOT NULL DEFAULT 0 CHECK (needs_value IN (0,1))
);

-- Legal animal class (species + sex/age/antler taxonomy). Rows are per season_year-agnostic
-- vocabulary; opportunities reference by (species_code, class_code).
CREATE TABLE regs.legal_animal_class (
  animal_class_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  species_code    VARCHAR(20) NOT NULL REFERENCES regs.species,
  class_code      VARCHAR(60) NOT NULL,
  display_label   VARCHAR(120) NOT NULL,
  CONSTRAINT uq_animal_class UNIQUE (species_code, class_code)
);

-- Decomposition of compound classes ("Brow-tined Bull OR Antlerless") for structured filtering.
CREATE TABLE regs.animal_class_part (
  animal_class_id BIGINT NOT NULL REFERENCES regs.legal_animal_class,
  part_seq        SMALLINT NOT NULL,
  sex_code        VARCHAR(12) CHECK (sex_code IN ('MALE','FEMALE','EITHER')),
  antler_code     VARCHAR(20),
  subspecies      VARCHAR(30),
  CONSTRAINT pk_animal_class_part PRIMARY KEY (animal_class_id, part_seq)
);

-- Down Migration
DROP TABLE IF EXISTS regs.animal_class_part;
DROP TABLE IF EXISTS regs.legal_animal_class;
DROP TABLE IF EXISTS regs.restriction_type;
DROP TABLE IF EXISTS regs.season_type;
DROP TABLE IF EXISTS regs.instrument_type;
DROP TABLE IF EXISTS regs.species;
DROP TABLE IF EXISTS regs.geography;
DROP TABLE IF EXISTS regs.region;
DROP TABLE IF EXISTS regs.source_document;
DROP TABLE IF EXISTS regs.season_year;
