-- ============================================================================
-- 0002_geography.sql — districts + district portions (no geometry here)
-- ----------------------------------------------------------------------------
-- Geometry is NOT stored in this DB. district_code / portion_code are the join
-- keys into FWP's live public ESRI layers (see 0019 regs.gis_layer + ADR-0061
-- addendum); geometry is resolved client-side. The former PostGIS sidecars (0011)
-- were retired in 0020 — the Oracle port therefore has no spatial component.
-- oracle-note: district_code is the verbatim ArcGIS DISTRICT string (preserves any
--   leading zeros); never delete a district — set last_season instead.
-- ============================================================================

-- Up Migration

CREATE TABLE regs.district (
  district_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  geography_code  VARCHAR(20) NOT NULL REFERENCES regs.geography,
  district_code   VARCHAR(10) NOT NULL,
  region_id       SMALLINT NOT NULL REFERENCES regs.region,
  district_name   VARCHAR(120),
  first_season    SMALLINT REFERENCES regs.season_year,
  last_season     SMALLINT REFERENCES regs.season_year,
  needs_review    SMALLINT NOT NULL DEFAULT 0 CHECK (needs_review IN (0,1)),
  CONSTRAINT uq_district UNIQUE (geography_code, district_code)
);
CREATE INDEX ix_district_region ON regs.district (region_id);

CREATE TABLE regs.district_portion (
  portion_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  district_id     BIGINT NOT NULL REFERENCES regs.district,
  portion_code    VARCHAR(40) NOT NULL,
  portion_name    VARCHAR(200) NOT NULL,
  boundary_desc   TEXT,
  has_geometry    SMALLINT NOT NULL DEFAULT 0 CHECK (has_geometry IN (0,1)),
  CONSTRAINT uq_portion UNIQUE (district_id, portion_code)
);
CREATE INDEX ix_portion_district ON regs.district_portion (district_id);

-- Down Migration
DROP TABLE IF EXISTS regs.district_portion;
DROP TABLE IF EXISTS regs.district;
