-- ============================================================================
-- 0003_hunt_areas.sql — the universal validity target
-- ----------------------------------------------------------------------------
-- Every opportunity is valid in exactly one hunt_area: a MATERIALIZED set of
-- districts and/or portions. Shorthand ("all R4 HDs except 455") is expanded to
-- explicit member rows at load time; the phrase is kept in definition_text. This
-- keeps read queries to a plain join (Oracle-portable; no recursive exclusion).
-- ============================================================================

-- Up Migration

CREATE TABLE regs.hunt_area (
  hunt_area_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year     SMALLINT NOT NULL REFERENCES regs.season_year,
  area_code       VARCHAR(60) NOT NULL,
  area_kind       VARCHAR(12) NOT NULL CHECK (area_kind IN ('DISTRICT','PORTION','MULTI')),
  definition_text VARCHAR(2000),
  CONSTRAINT uq_hunt_area UNIQUE (season_year, area_code)
);

CREATE TABLE regs.hunt_area_member (
  hunt_area_id  BIGINT NOT NULL REFERENCES regs.hunt_area,
  member_seq    SMALLINT NOT NULL,
  district_id   BIGINT REFERENCES regs.district,
  portion_id    BIGINT REFERENCES regs.district_portion,
  CONSTRAINT pk_hunt_area_member PRIMARY KEY (hunt_area_id, member_seq),
  CONSTRAINT ck_ham_one_target CHECK (
    (district_id IS NOT NULL AND portion_id IS NULL) OR
    (district_id IS NULL AND portion_id IS NOT NULL))
);
CREATE INDEX ix_ham_district ON regs.hunt_area_member (district_id);
CREATE INDEX ix_ham_portion  ON regs.hunt_area_member (portion_id);

-- Down Migration
DROP TABLE IF EXISTS regs.hunt_area_member;
DROP TABLE IF EXISTS regs.hunt_area;
