-- ============================================================================
-- 0004_instruments.sql — license/permit instruments
-- ----------------------------------------------------------------------------
-- The commission quota RANGE is enforced by the database itself (ck_li_quota_in_range):
-- FWP staff can adjust quota_current mid-season but never outside quota_min..quota_max.
-- Generals use a synthetic code 'GEN-<species>' so instr_code is NOT NULL and the
-- uniqueness constraint is a plain UNIQUE (no partial index → Oracle-portable).
-- ============================================================================

-- Up Migration

CREATE TABLE regs.license_instrument (
  instrument_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year     SMALLINT NOT NULL REFERENCES regs.season_year,
  instr_type_code VARCHAR(20) NOT NULL REFERENCES regs.instrument_type,
  species_code    VARCHAR(20) NOT NULL REFERENCES regs.species,
  instr_code      VARCHAR(12) NOT NULL,
  display_name    VARCHAR(120) NOT NULL,
  is_draw         SMALLINT NOT NULL CHECK (is_draw IN (0,1)),
  apply_by        DATE,
  otc_from        DATE,
  quota_current   INTEGER,
  quota_unlimited SMALLINT NOT NULL DEFAULT 0 CHECK (quota_unlimited IN (0,1)),
  quota_min       INTEGER,
  quota_max       INTEGER,
  per_hunter_max  SMALLINT DEFAULT 1,
  record_status   VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
                  CHECK (record_status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  revision        INTEGER NOT NULL DEFAULT 1,
  updated_by      VARCHAR(120) NOT NULL DEFAULT 'system',
  updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_doc_id   BIGINT REFERENCES regs.source_document,
  source_page     SMALLINT,
  raw_text        TEXT,
  CONSTRAINT uq_license_instrument UNIQUE (season_year, instr_code),
  CONSTRAINT ck_li_quota_range CHECK
    (quota_min IS NULL OR quota_max IS NULL OR quota_min <= quota_max),
  CONSTRAINT ck_li_quota_in_range CHECK
    (quota_current IS NULL OR quota_min IS NULL OR quota_max IS NULL
      OR (quota_current BETWEEN quota_min AND quota_max))
);
CREATE INDEX ix_li_year_status ON regs.license_instrument (season_year, record_status);
CREATE INDEX ix_li_species     ON regs.license_instrument (season_year, species_code);

-- Down Migration
DROP TABLE IF EXISTS regs.license_instrument;
