-- ============================================================================
-- 0005_opportunities.sql — opportunities, season windows, restrictions
-- ----------------------------------------------------------------------------
-- An opportunity = one printed row/sub-row = instrument × animal class × hunt area
-- (+ split_seq for sub-row splits sharing an instrument). Real dates in season_window
-- are authoritative; raw_range is kept verbatim so the legacy flat view emits exactly
-- what the web app's seasonWindow.ts already parses.
-- ============================================================================

-- Up Migration

CREATE TABLE regs.opportunity (
  opportunity_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year      SMALLINT NOT NULL REFERENCES regs.season_year,
  instrument_id    BIGINT NOT NULL REFERENCES regs.license_instrument,
  animal_class_id  BIGINT NOT NULL REFERENCES regs.legal_animal_class,
  hunt_area_id     BIGINT NOT NULL REFERENCES regs.hunt_area,
  split_seq        SMALLINT NOT NULL DEFAULT 1,
  home_district_id BIGINT REFERENCES regs.district,
  print_order      SMALLINT,
  validity_note    VARCHAR(2000),
  record_status    VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
                   CHECK (record_status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  revision         INTEGER NOT NULL DEFAULT 1,
  updated_by       VARCHAR(120) NOT NULL DEFAULT 'system',
  updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_doc_id    BIGINT REFERENCES regs.source_document,
  source_page      SMALLINT,
  raw_text         TEXT,
  CONSTRAINT uq_opportunity UNIQUE (instrument_id, animal_class_id, hunt_area_id, split_seq)
);
CREATE INDEX ix_opp_year   ON regs.opportunity (season_year, record_status);
CREATE INDEX ix_opp_area   ON regs.opportunity (hunt_area_id);
CREATE INDEX ix_opp_homehd ON regs.opportunity (home_district_id);

CREATE TABLE regs.season_window (
  window_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id   BIGINT NOT NULL REFERENCES regs.opportunity ON DELETE CASCADE,
  season_type_code VARCHAR(20) NOT NULL REFERENCES regs.season_type,
  window_seq       SMALLINT NOT NULL DEFAULT 1,
  starts_on        DATE NOT NULL,
  ends_on          DATE NOT NULL,
  raw_range        VARCHAR(60),
  CONSTRAINT uq_season_window UNIQUE (opportunity_id, season_type_code, window_seq),
  CONSTRAINT ck_window_order CHECK (starts_on <= ends_on)
);
CREATE INDEX ix_window_opp ON regs.season_window (opportunity_id);

CREATE TABLE regs.opp_restriction (
  opportunity_id BIGINT NOT NULL REFERENCES regs.opportunity ON DELETE CASCADE,
  restr_seq      SMALLINT NOT NULL,
  restr_code     VARCHAR(30) NOT NULL REFERENCES regs.restriction_type,
  value_text     VARCHAR(200),
  raw_text       VARCHAR(2000) NOT NULL,
  CONSTRAINT pk_opp_restriction PRIMARY KEY (opportunity_id, restr_seq)
);

-- Down Migration
DROP TABLE IF EXISTS regs.opp_restriction;
DROP TABLE IF EXISTS regs.season_window;
DROP TABLE IF EXISTS regs.opportunity;
