-- ============================================================================
-- 0006_restricted_notes.sql — restricted areas, WRAs, per-district notes
-- ============================================================================

-- Up Migration

CREATE TABLE regs.restricted_area (
  rarea_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year   SMALLINT NOT NULL REFERENCES regs.season_year,
  area_type     VARCHAR(20) NOT NULL CHECK (area_type IN
                ('RESTRICTED','WEAPONS_RESTR','CLOSURE','ARCHERY_ONLY')),
  area_name     VARCHAR(200) NOT NULL,
  legal_desc    TEXT,
  source_doc_id BIGINT REFERENCES regs.source_document,
  source_page   SMALLINT,
  CONSTRAINT uq_restricted_area UNIQUE (season_year, area_name)
);

CREATE TABLE regs.district_rarea (
  district_id BIGINT NOT NULL REFERENCES regs.district,
  rarea_id    BIGINT NOT NULL REFERENCES regs.restricted_area,
  note        VARCHAR(1000),
  CONSTRAINT pk_district_rarea PRIMARY KEY (district_id, rarea_id)
);

CREATE TABLE regs.district_note (
  note_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year   SMALLINT NOT NULL REFERENCES regs.season_year,
  district_id   BIGINT NOT NULL REFERENCES regs.district,
  species_code  VARCHAR(20) REFERENCES regs.species,
  note_text     VARCHAR(2000) NOT NULL,
  note_seq      SMALLINT NOT NULL DEFAULT 1,
  record_status VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
                CHECK (record_status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  updated_by    VARCHAR(120) NOT NULL DEFAULT 'system',
  updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_doc_id BIGINT REFERENCES regs.source_document,
  source_page   SMALLINT
);
CREATE INDEX ix_note_district ON regs.district_note (season_year, district_id);

-- License-product placeholder (fees) — ship empty; no UI in v1.
CREATE TABLE regs.license_product (
  product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year     SMALLINT REFERENCES regs.season_year,
  product_code    VARCHAR(40) NOT NULL,
  display_name    VARCHAR(120) NOT NULL,
  species_code    VARCHAR(20) REFERENCES regs.species,
  fee_res_cents      INTEGER,
  fee_nonres_cents   INTEGER,
  fee_youth_cents    INTEGER,
  fee_disabled_cents INTEGER,
  CONSTRAINT uq_license_product UNIQUE (season_year, product_code)
);

-- Down Migration
DROP TABLE IF EXISTS regs.license_product;
DROP TABLE IF EXISTS regs.district_note;
DROP TABLE IF EXISTS regs.district_rarea;
DROP TABLE IF EXISTS regs.restricted_area;
