-- ============================================================================
-- 0007_workflow_audit.sql — publication snapshots + append-only audit trail
-- ----------------------------------------------------------------------------
-- published_regulations is the IMMUTABLE flattened snapshot (NormalizedRegulation
-- shape) the public API reads — editing-schema churn can never break the public
-- contract. The audit trigger + trigger function are the ONE per-platform rewrite
-- for Oracle (SYS_CONTEXT client id + JSON_OBJECT(*)); documented in the runbook.
-- ============================================================================

-- Up Migration

CREATE TABLE regs.publication (
  publication_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year    SMALLINT NOT NULL REFERENCES regs.season_year,
  version        INTEGER NOT NULL,
  published_by   VARCHAR(120) NOT NULL,
  published_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note           VARCHAR(1000),
  CONSTRAINT uq_publication UNIQUE (season_year, version)
);

-- Immutable flattened snapshot in the NormalizedRegulation shape.
-- oracle-note: weapon_windows is a JSON string (TEXT → CLOB); region is nullable INT.
CREATE TABLE regs.published_regulations (
  season_year          SMALLINT NOT NULL REFERENCES regs.season_year,
  version              INTEGER NOT NULL,
  rule_id              VARCHAR(120) NOT NULL,
  species              VARCHAR(20) NOT NULL,
  species_group        VARCHAR(20) NOT NULL,
  geography_type       VARCHAR(20) NOT NULL,
  geography_id         VARCHAR(20) NOT NULL,
  region               INTEGER,
  district_name        VARCHAR(120),
  legal_animal         VARCHAR(120) NOT NULL,
  required_license     VARCHAR(120) NOT NULL,
  is_draw              SMALLINT NOT NULL CHECK (is_draw IN (0,1)),
  weapon_windows       TEXT NOT NULL,
  quota                INTEGER,
  apply_by_date        VARCHAR(30),
  opportunity_specific VARCHAR(2000),
  effective_date       VARCHAR(10) NOT NULL,
  expires_date         VARCHAR(10),
  source_reg_id        VARCHAR(60) NOT NULL,
  CONSTRAINT pk_published_regulations PRIMARY KEY (season_year, version, rule_id)
);
CREATE INDEX ix_pubreg_lookup ON regs.published_regulations
  (season_year, version, species, geography_type, geography_id);

CREATE TABLE regs.audit_log (
  audit_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name     VARCHAR(30) NOT NULL,
  row_pk         BIGINT NOT NULL,
  action_code    VARCHAR(10) NOT NULL CHECK (action_code IN ('INSERT','UPDATE','DELETE','PUBLISH')),
  changed_by     VARCHAR(120) NOT NULL,
  changed_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  publication_id BIGINT REFERENCES regs.publication,
  old_row_json   TEXT,
  new_row_json   TEXT
);
CREATE INDEX ix_audit_table ON regs.audit_log (table_name, row_pk);
CREATE INDEX ix_audit_when  ON regs.audit_log (changed_at);

-- oracle-note: the trigger function + attached triggers are the ONE per-platform
-- rewrite. Oracle: compound trigger using JSON_OBJECT(*) and SYS_CONTEXT('..','..').
CREATE OR REPLACE FUNCTION regs.fn_audit_row() RETURNS trigger AS $$
DECLARE
  acting_user VARCHAR(120);
  pk_value    BIGINT;
BEGIN
  acting_user := COALESCE(current_setting('app.user', true), 'system');
  IF (TG_OP = 'DELETE') THEN
    pk_value := (to_jsonb(OLD) ->> (TG_ARGV[0]))::bigint;
    INSERT INTO regs.audit_log (table_name, row_pk, action_code, changed_by, old_row_json)
    VALUES (TG_TABLE_NAME, pk_value, 'DELETE', acting_user, row_to_json(OLD)::text);
    RETURN OLD;
  ELSIF (TG_OP = 'UPDATE') THEN
    pk_value := (to_jsonb(NEW) ->> (TG_ARGV[0]))::bigint;
    INSERT INTO regs.audit_log (table_name, row_pk, action_code, changed_by, old_row_json, new_row_json)
    VALUES (TG_TABLE_NAME, pk_value, 'UPDATE', acting_user, row_to_json(OLD)::text, row_to_json(NEW)::text);
    RETURN NEW;
  ELSE
    pk_value := (to_jsonb(NEW) ->> (TG_ARGV[0]))::bigint;
    INSERT INTO regs.audit_log (table_name, row_pk, action_code, changed_by, new_row_json)
    VALUES (TG_TABLE_NAME, pk_value, 'INSERT', acting_user, row_to_json(NEW)::text);
    RETURN NEW;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Attach to the mutable regulatory tables (pk column name passed as trigger arg).
CREATE TRIGGER trg_audit_instrument AFTER INSERT OR UPDATE OR DELETE ON regs.license_instrument
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('instrument_id');
CREATE TRIGGER trg_audit_opportunity AFTER INSERT OR UPDATE OR DELETE ON regs.opportunity
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('opportunity_id');
CREATE TRIGGER trg_audit_note AFTER INSERT OR UPDATE OR DELETE ON regs.district_note
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('note_id');
CREATE TRIGGER trg_audit_hunt_area AFTER INSERT OR UPDATE OR DELETE ON regs.hunt_area
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('hunt_area_id');
CREATE TRIGGER trg_audit_rarea AFTER INSERT OR UPDATE OR DELETE ON regs.restricted_area
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('rarea_id');

-- Down Migration
DROP TRIGGER IF EXISTS trg_audit_rarea ON regs.restricted_area;
DROP TRIGGER IF EXISTS trg_audit_hunt_area ON regs.hunt_area;
DROP TRIGGER IF EXISTS trg_audit_note ON regs.district_note;
DROP TRIGGER IF EXISTS trg_audit_opportunity ON regs.opportunity;
DROP TRIGGER IF EXISTS trg_audit_instrument ON regs.license_instrument;
DROP FUNCTION IF EXISTS regs.fn_audit_row();
DROP TABLE IF EXISTS regs.audit_log;
DROP TABLE IF EXISTS regs.published_regulations;
DROP TABLE IF EXISTS regs.publication;
