-- ============================================================================
-- 0008_auth.sql — staff users + sessions
-- ----------------------------------------------------------------------------
-- Real email/password auth (argon2id) for today; behind an AuthProvider interface
-- so the Oracle-era XMT OAuth provider slots in with sessions unchanged. Session
-- ids are stored hashed (never the raw token).
-- ============================================================================

-- Up Migration

CREATE TABLE regs.staff_user (
  user_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email             VARCHAR(200) NOT NULL,
  password_hash     VARCHAR(255) NOT NULL,
  display_name      VARCHAR(120) NOT NULL,
  role              VARCHAR(20) NOT NULL DEFAULT 'viewer'
                    CHECK (role IN ('viewer','editor','approver','admin')),
  must_reset        SMALLINT NOT NULL DEFAULT 0 CHECK (must_reset IN (0,1)),
  is_active_flag    SMALLINT NOT NULL DEFAULT 1 CHECK (is_active_flag IN (0,1)),
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_staff_email UNIQUE (email)
);

CREATE TABLE regs.staff_session (
  session_hash  VARCHAR(64) PRIMARY KEY,      -- sha-256 hex of the raw session id
  user_id       BIGINT NOT NULL REFERENCES regs.staff_user,
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
  ip            VARCHAR(64),
  user_agent    VARCHAR(400)
);
CREATE INDEX ix_session_user ON regs.staff_session (user_id);
CREATE INDEX ix_session_exp  ON regs.staff_session (expires_at);

-- Down Migration
DROP TABLE IF EXISTS regs.staff_session;
DROP TABLE IF EXISTS regs.staff_user;
