-- ============================================================================
-- 0009_staging.sql — ETL staging tables (raw landing before promotion to regs.*)
-- ----------------------------------------------------------------------------
-- Loaders write here first; a QA report runs; only then rows promote to the
-- normalized tables as DRAFT. Never bulk-insert straight to published.
-- ============================================================================

-- Up Migration

-- One row per flat DEA JSON row (Phase A seed corpus).
CREATE TABLE regs.stg_dea_row (
  stg_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year      SMALLINT NOT NULL,
  hd               VARCHAR(10),
  district_name    VARCHAR(120),
  region           SMALLINT,
  species          VARCHAR(20),
  license          VARCHAR(200),
  opportunity      VARCHAR(200),
  apply_by_date    VARCHAR(40),
  quota            INTEGER,
  quota_range      VARCHAR(40),
  early_dates      VARCHAR(60),
  archery_dates    VARCHAR(60),
  general_dates    VARCHAR(60),
  heritage_ml_dates VARCHAR(60),
  late_dates       VARCHAR(60),
  opp_specific     VARCHAR(2000),
  district_notes   TEXT,
  raw_row          TEXT,
  load_status      VARCHAR(20) NOT NULL DEFAULT 'NEW'
                   CHECK (load_status IN ('NEW','PROMOTED','QUARANTINED')),
  quarantine_reason VARCHAR(200)
);
CREATE INDEX ix_stg_dea_hd ON regs.stg_dea_row (season_year, hd);

-- Multi-district validity table (printed pp.128-129) — one row per code.
CREATE TABLE regs.stg_multi_district (
  stg_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year  SMALLINT NOT NULL,
  instr_code   VARCHAR(12) NOT NULL,
  lpt_type     VARCHAR(40),
  hd_list_text VARCHAR(1000) NOT NULL,
  caveat       VARCHAR(1000),
  expanded     SMALLINT NOT NULL DEFAULT 0 CHECK (expanded IN (0,1))
);

-- Down Migration
DROP TABLE IF EXISTS regs.stg_multi_district;
DROP TABLE IF EXISTS regs.stg_dea_row;
