-- ============================================================================
-- 0013_license_fees.sql — full license fee model (replaces the empty placeholder)
-- ----------------------------------------------------------------------------
-- Printed fee/availability charts pp.12-13. One product per printed chart row;
-- discounted variants (NR-native, youth-sponsored, college) are AUDIENCE PRICE ROWS
-- on the same product, not separate products — mirrors the book exactly.
-- The empty license_product (0006) has no data/UI, so DROP + recreate is cleaner
-- than a column-by-column ALTER.
-- ============================================================================

-- Up Migration

-- Audience = pricing tier (seeded by seed.ts alongside the other vocabularies).
CREATE TABLE regs.audience (
  audience_code VARCHAR(20) PRIMARY KEY,
  display_name  VARCHAR(80) NOT NULL,
  residency     VARCHAR(3) NOT NULL CHECK (residency IN ('RES','NR')),
  sort_order    SMALLINT NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS regs.license_product;
CREATE TABLE regs.license_product (
  product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year     SMALLINT NOT NULL REFERENCES regs.season_year,
  product_code    VARCHAR(40) NOT NULL,
  display_name    VARCHAR(160) NOT NULL,
  product_kind    VARCHAR(20) NOT NULL CHECK (product_kind IN
                  ('PREREQUISITE','LICENSE','PERMIT','COMBO','B_LICENSE','SURCHARGE')),
  species_code    VARCHAR(20) REFERENCES regs.species,
  instr_type_code VARCHAR(20) REFERENCES regs.instrument_type,
  apply_by        DATE,
  otc_note        VARCHAR(400),
  chart_note      VARCHAR(1000),
  sort_order      SMALLINT NOT NULL DEFAULT 0,
  record_status   VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
                  CHECK (record_status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  revision        INTEGER NOT NULL DEFAULT 1,
  updated_by      VARCHAR(120) NOT NULL DEFAULT 'system',
  updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_doc_id   BIGINT REFERENCES regs.source_document,
  source_page     SMALLINT,
  CONSTRAINT uq_license_product UNIQUE (season_year, product_code)
);
CREATE INDEX ix_product_year ON regs.license_product (season_year, record_status);

CREATE TABLE regs.product_price (
  price_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    BIGINT NOT NULL REFERENCES regs.license_product ON DELETE CASCADE,
  audience_code VARCHAR(20) NOT NULL REFERENCES regs.audience,
  price_cents   INTEGER NOT NULL CHECK (price_cents >= 0),
  price_note    VARCHAR(400),
  CONSTRAINT uq_product_price UNIQUE (product_id, audience_code)
);

-- Immutable publish snapshot (public v2 reads ONLY this).
CREATE TABLE regs.published_fees (
  season_year   SMALLINT NOT NULL,
  version       INTEGER  NOT NULL,
  product_code  VARCHAR(40) NOT NULL,
  display_name  VARCHAR(160) NOT NULL,
  product_kind  VARCHAR(20) NOT NULL,
  species_code  VARCHAR(20),
  audience_code VARCHAR(20) NOT NULL,
  price_cents   INTEGER NOT NULL,
  apply_by      VARCHAR(30),
  chart_note    VARCHAR(1000),
  price_note    VARCHAR(400),
  sort_order    SMALLINT NOT NULL,
  CONSTRAINT pk_published_fees PRIMARY KEY (season_year, version, product_code, audience_code)
);

CREATE TRIGGER trg_audit_product AFTER INSERT OR UPDATE OR DELETE ON regs.license_product
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('product_id');

-- Down Migration
DROP TRIGGER IF EXISTS trg_audit_product ON regs.license_product;
DROP TABLE IF EXISTS regs.published_fees;
DROP TABLE IF EXISTS regs.product_price;
DROP TABLE IF EXISTS regs.license_product;
DROP TABLE IF EXISTS regs.audience;
-- Recreate the original empty placeholder so the down-migration restores 0006's shape.
CREATE TABLE regs.license_product (
  product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year     SMALLINT REFERENCES regs.season_year,
  product_code    VARCHAR(40) NOT NULL,
  display_name    VARCHAR(120) NOT NULL,
  species_code    VARCHAR(20) REFERENCES regs.species,
  fee_res_cents      INTEGER,
  fee_nonres_cents   INTEGER,
  fee_youth_cents    INTEGER,
  fee_disabled_cents INTEGER,
  CONSTRAINT uq_license_product UNIQUE (season_year, product_code)
);
