-- ============================================================================
-- 0014_content_sections.sql — reference content (laws & rules, hunter orange, etc.)
-- ----------------------------------------------------------------------------
-- The book's prose sections (definitions, licensing, ~35 Laws & Rules statute
-- sections, youth/disability, drawing explainers, access, contacts). Structured
-- tables (refund, restitution, youth chart) live as GFM pipe tables INSIDE body_md:
-- one editor, one renderer, and the print exporter parses GFM tables into ICML
-- <Table> anyway — so they're machine-readable, not opaque prose.
-- Drawing "statistics" (pp.43-45, p.137) are DRAWING-category content, NOT numeric
-- tables — the printed example is explicitly disclaimed as non-factual. A future
-- numeric regs.draw_stat table (fed by FWP's drawing-results system) is out of scope.
-- ============================================================================

-- Up Migration

CREATE TABLE regs.content_section (
  section_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year   SMALLINT NOT NULL REFERENCES regs.season_year,
  slug          VARCHAR(80) NOT NULL,
  category      VARCHAR(20) NOT NULL CHECK (category IN
                ('DEFINITIONS','LICENSING','LAWS_RULES','YOUTH','DISABILITY',
                 'DRAWING','SAFETY','ACCESS','OTHER')),
  title         VARCHAR(200) NOT NULL,
  body_md       TEXT NOT NULL,             -- oracle-note: CLOB
  statute_refs  VARCHAR(400),              -- 'MCA 87-6-414; ARM 12.9.107' — semicolon list
  sort_order    SMALLINT NOT NULL DEFAULT 0,
  record_status VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
                CHECK (record_status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  revision      INTEGER NOT NULL DEFAULT 1,
  updated_by    VARCHAR(120) NOT NULL DEFAULT 'system',
  updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_doc_id BIGINT REFERENCES regs.source_document,
  source_page   SMALLINT,
  CONSTRAINT uq_content_section UNIQUE (season_year, slug)
);
CREATE INDEX ix_content_year_cat ON regs.content_section (season_year, category, sort_order);

CREATE TABLE regs.published_content (
  season_year  SMALLINT NOT NULL,
  version      INTEGER  NOT NULL,
  slug         VARCHAR(80) NOT NULL,
  category     VARCHAR(20) NOT NULL,
  title        VARCHAR(200) NOT NULL,
  body_md      TEXT NOT NULL,
  statute_refs VARCHAR(400),
  sort_order   SMALLINT NOT NULL,
  CONSTRAINT pk_published_content PRIMARY KEY (season_year, version, slug)
);

CREATE TRIGGER trg_audit_content AFTER INSERT OR UPDATE OR DELETE ON regs.content_section
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('section_id');

-- Down Migration
DROP TRIGGER IF EXISTS trg_audit_content ON regs.content_section;
DROP TABLE IF EXISTS regs.published_content;
DROP TABLE IF EXISTS regs.content_section;
