-- ============================================================================
-- 0015_sunrise_sunset.sql — official commission-adopted shooting-hours tables (p.151)
-- ----------------------------------------------------------------------------
-- 4 zones × county lists × a per-day Aug–Feb sunrise/sunset grid. Times are
-- minutes-after-midnight SMALLINT (oracle-note: Oracle has no native TIME; SMALLINT
-- ports verbatim and avoids TZ ambiguity). month_no/day_no not DATE: the printed grid
-- spans a calendar-year boundary and is season-year-scoped.
-- ============================================================================

-- Up Migration

CREATE TABLE regs.ss_zone (
  ss_zone_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year SMALLINT NOT NULL REFERENCES regs.season_year,
  zone_no     SMALLINT NOT NULL CHECK (zone_no BETWEEN 1 AND 4),
  zone_name   VARCHAR(60) NOT NULL,
  CONSTRAINT uq_ss_zone UNIQUE (season_year, zone_no)
);

CREATE TABLE regs.ss_zone_county (
  ss_zone_id  BIGINT NOT NULL REFERENCES regs.ss_zone ON DELETE CASCADE,
  county_name VARCHAR(40) NOT NULL,
  county_fips VARCHAR(5),
  CONSTRAINT pk_ss_zone_county PRIMARY KEY (ss_zone_id, county_name)
);

CREATE TABLE regs.ss_time (
  ss_zone_id  BIGINT NOT NULL REFERENCES regs.ss_zone ON DELETE CASCADE,
  month_no    SMALLINT NOT NULL CHECK (month_no BETWEEN 1 AND 12),
  day_no      SMALLINT NOT NULL CHECK (day_no BETWEEN 1 AND 31),
  rise_min    SMALLINT NOT NULL CHECK (rise_min BETWEEN 0 AND 1439),
  set_min     SMALLINT NOT NULL CHECK (set_min BETWEEN 0 AND 1439),
  CONSTRAINT pk_ss_time PRIMARY KEY (ss_zone_id, month_no, day_no)
);

-- Down Migration
DROP TABLE IF EXISTS regs.ss_time;
DROP TABLE IF EXISTS regs.ss_zone_county;
DROP TABLE IF EXISTS regs.ss_zone;
