-- ============================================================================
-- 0016_cms_assets.sql — Bloomreach CMS asset registry + the book's map inventory
-- ----------------------------------------------------------------------------
-- Every map/figure in the book (region plates pp.30-41 deer/elk + pp.130-136 antelope,
-- CWD samples map, bear distribution, sunrise-sunset zone map, cover, per-restricted-
-- area maps) is a CMS asset sourced from FWP's Bloomreach CMS. cms_doc_id is the
-- Bloomreach document id (stub rows use 'stub:<slug>'); the real Delivery-API client
-- resolves cached_url. Link tables relate assets to regions/areas/content.
-- ============================================================================

-- Up Migration

CREATE TABLE regs.cms_asset (
  asset_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cms_provider VARCHAR(20) NOT NULL DEFAULT 'BLOOMREACH',
  cms_doc_id   VARCHAR(160) NOT NULL,
  cms_path     VARCHAR(400),
  asset_kind   VARCHAR(20) NOT NULL CHECK (asset_kind IN
               ('REGION_MAP','DISTRICT_MAP','ZONE_MAP','AREA_MAP','FIGURE','COVER')),
  title        VARCHAR(200) NOT NULL,
  caption      VARCHAR(1000),
  alt_text     VARCHAR(400),
  season_year  SMALLINT REFERENCES regs.season_year,   -- NULL = evergreen
  cached_url   VARCHAR(1000),
  cached_at    TIMESTAMP WITH TIME ZONE,
  updated_by   VARCHAR(120) NOT NULL DEFAULT 'system',
  updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_cms_asset UNIQUE (cms_provider, cms_doc_id)
);

-- The per-region map plate for a species geography (one plate per region × geography).
CREATE TABLE regs.region_asset (
  region_id      SMALLINT NOT NULL REFERENCES regs.region,
  geography_code VARCHAR(20) NOT NULL REFERENCES regs.geography,
  asset_id       BIGINT NOT NULL REFERENCES regs.cms_asset,
  CONSTRAINT pk_region_asset PRIMARY KEY (region_id, geography_code)
);

CREATE TABLE regs.rarea_asset (
  rarea_id BIGINT NOT NULL REFERENCES regs.restricted_area,
  asset_id BIGINT NOT NULL REFERENCES regs.cms_asset,
  CONSTRAINT pk_rarea_asset PRIMARY KEY (rarea_id, asset_id)
);

CREATE TABLE regs.content_asset (
  section_id BIGINT NOT NULL REFERENCES regs.content_section,
  asset_id   BIGINT NOT NULL REFERENCES regs.cms_asset,
  sort_order SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT pk_content_asset PRIMARY KEY (section_id, asset_id)
);

CREATE TRIGGER trg_audit_cms_asset AFTER INSERT OR UPDATE OR DELETE ON regs.cms_asset
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('asset_id');

-- Down Migration
DROP TRIGGER IF EXISTS trg_audit_cms_asset ON regs.cms_asset;
DROP TABLE IF EXISTS regs.content_asset;
DROP TABLE IF EXISTS regs.rarea_asset;
DROP TABLE IF EXISTS regs.region_asset;
DROP TABLE IF EXISTS regs.cms_asset;
