-- ============================================================================
-- 0017_staging_phase_b.sql — Phase-B staging tables + MGMT_ZONE widening
-- ----------------------------------------------------------------------------
-- Machine-extracted Phase-B content lands here before promotion (staging→QA→DRAFT).
-- Also widens restricted_area.area_type for CWD Management Zones ("Libby CWD
-- Management Zone", Deer B 199-20). Fees/content are hand-curated seed files reviewed
-- via git diff, so they skip staging by design.
-- ============================================================================

-- Up Migration

ALTER TABLE regs.restricted_area DROP CONSTRAINT restricted_area_area_type_check;
ALTER TABLE regs.restricted_area ADD CONSTRAINT restricted_area_area_type_check
  CHECK (area_type IN ('RESTRICTED','WEAPONS_RESTR','CLOSURE','ARCHERY_ONLY','MGMT_ZONE'));

CREATE TABLE regs.stg_youth_pthfv (
  stg_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year  SMALLINT NOT NULL,
  program      VARCHAR(20) NOT NULL CHECK (program IN ('YOUTH','PTHFV')),
  species      VARCHAR(20),
  hd_list_text VARCHAR(2000) NOT NULL,
  legal_animal VARCHAR(200),
  date_text    VARCHAR(120),
  caveat       VARCHAR(1000),
  load_status  VARCHAR(20) NOT NULL DEFAULT 'NEW'
               CHECK (load_status IN ('NEW','PROMOTED','QUARANTINED')),
  quarantine_reason VARCHAR(200)
);

CREATE TABLE regs.stg_restricted_area (
  stg_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year SMALLINT NOT NULL,
  area_name   VARCHAR(200) NOT NULL,
  area_type   VARCHAR(20),
  legal_desc  TEXT,
  hd_refs     VARCHAR(400),
  source_page SMALLINT,
  load_status VARCHAR(20) NOT NULL DEFAULT 'NEW'
              CHECK (load_status IN ('NEW','PROMOTED','QUARANTINED')),
  quarantine_reason VARCHAR(200)
);

CREATE TABLE regs.stg_antelope_row (
  stg_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year   SMALLINT NOT NULL,
  hd            VARCHAR(10),
  district_name VARCHAR(120),
  region        SMALLINT,
  license       VARCHAR(200),
  legal_animal  VARCHAR(200),
  archery_dates VARCHAR(60),
  general_dates VARCHAR(60),
  quota         INTEGER,
  quota_range   VARCHAR(40),
  apply_by_date VARCHAR(40),
  opp_specific  VARCHAR(2000),
  raw_row       TEXT,
  source_page   SMALLINT,
  load_status   VARCHAR(20) NOT NULL DEFAULT 'NEW'
                CHECK (load_status IN ('NEW','PROMOTED','QUARANTINED')),
  quarantine_reason VARCHAR(200)
);

CREATE TABLE regs.stg_ss_time (
  stg_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year       SMALLINT NOT NULL,
  zone_no           SMALLINT NOT NULL,
  month_no          SMALLINT NOT NULL,
  day_no            SMALLINT NOT NULL,
  rise_text         VARCHAR(10) NOT NULL,
  set_text          VARCHAR(10) NOT NULL,
  computed_rise_min SMALLINT,
  computed_set_min  SMALLINT,
  load_status       VARCHAR(20) NOT NULL DEFAULT 'NEW'
                    CHECK (load_status IN ('NEW','PROMOTED','QUARANTINED')),
  quarantine_reason VARCHAR(200)
);

-- Down Migration
DROP TABLE IF EXISTS regs.stg_ss_time;
DROP TABLE IF EXISTS regs.stg_antelope_row;
DROP TABLE IF EXISTS regs.stg_restricted_area;
DROP TABLE IF EXISTS regs.stg_youth_pthfv;
ALTER TABLE regs.restricted_area DROP CONSTRAINT restricted_area_area_type_check;
ALTER TABLE regs.restricted_area ADD CONSTRAINT restricted_area_area_type_check
  CHECK (area_type IN ('RESTRICTED','WEAPONS_RESTR','CLOSURE','ARCHERY_ONLY'));
