-- ============================================================================
-- 0022_important_dates.sql — the book's "Important Dates" tables (printed p.11)
-- ----------------------------------------------------------------------------
-- Season dates, application/purchase deadlines, drawing-result + refund-mailed dates,
-- and the scattered purchase windows (OTC June 15, bonus-point July 1-Sept 30, game-
-- damage-roster June 15-July 15, shed-hunting May 15). One row per printed date line;
-- species_scope is free text ("Deer & Elk", "Antelope", "All") to match the book, which
-- groups deer + elk. Editable + audited + published like license_product.
-- ============================================================================

-- Up Migration

CREATE TABLE regs.important_date (
  important_date_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year   SMALLINT NOT NULL REFERENCES regs.season_year,
  date_code     VARCHAR(60) NOT NULL,          -- stable slug for the publish snapshot key
  date_kind     VARCHAR(20) NOT NULL CHECK (date_kind IN
                ('SEASON','DEADLINE','DRAWING_RESULT','REFUND','PURCHASE_WINDOW')),
  species_scope VARCHAR(60),                    -- free text: 'Deer & Elk', 'Antelope', 'All'
  label         VARCHAR(200) NOT NULL,
  starts_on     DATE,                           -- nullable: some entries are descriptive
  ends_on       DATE,
  note          VARCHAR(600),
  sort_order    SMALLINT NOT NULL DEFAULT 0,
  record_status VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
                CHECK (record_status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  revision      INTEGER NOT NULL DEFAULT 1,
  updated_by    VARCHAR(120) NOT NULL DEFAULT 'system',
  updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_doc_id BIGINT REFERENCES regs.source_document,
  source_page   SMALLINT,
  CONSTRAINT uq_important_date UNIQUE (season_year, date_code)
);
CREATE INDEX ix_important_date_year ON regs.important_date (season_year, date_kind, sort_order);

-- Immutable publish snapshot (public v2 reads ONLY this).
CREATE TABLE regs.published_important_dates (
  season_year   SMALLINT NOT NULL,
  version       INTEGER  NOT NULL,
  date_code     VARCHAR(60) NOT NULL,
  date_kind     VARCHAR(20) NOT NULL,
  species_scope VARCHAR(60),
  label         VARCHAR(200) NOT NULL,
  starts_on     DATE,
  ends_on       DATE,
  note          VARCHAR(600),
  sort_order    SMALLINT NOT NULL,
  CONSTRAINT pk_published_important_dates PRIMARY KEY (season_year, version, date_code)
);

CREATE TRIGGER trg_audit_important_date AFTER INSERT OR UPDATE OR DELETE ON regs.important_date
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('important_date_id');

-- Down Migration
DROP TRIGGER IF EXISTS trg_audit_important_date ON regs.important_date;
DROP TABLE IF EXISTS regs.published_important_dates;
DROP TABLE IF EXISTS regs.important_date;
