-- ============================================================================
-- 0023_contacts.sql — the book's Contact List (printed pp.143-144) + bear specialists
-- ----------------------------------------------------------------------------
-- FWP State HQ + hotlines, the seven Regional HQs and field offices, non-FWP state
-- agencies, federal agencies, tribal governments (pp.143-144), plus the bear-management
-- specialists (p.47) and the MonTECH assistive-tech contact (p.20). One row per contact;
-- contact_kind groups them. Editable + audited + published like license_product.
-- ============================================================================

-- Up Migration

CREATE TABLE regs.contact (
  contact_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year   SMALLINT NOT NULL REFERENCES regs.season_year,
  contact_code  VARCHAR(60) NOT NULL,          -- stable slug for the publish snapshot key
  contact_kind  VARCHAR(20) NOT NULL CHECK (contact_kind IN
                ('STATE_HQ','HOTLINE','REGIONAL_HQ','FIELD_OFFICE','STATE_AGENCY',
                 'FEDERAL','TRIBAL','BEAR_SPECIALIST','OTHER')),
  name          VARCHAR(160) NOT NULL,
  org           VARCHAR(160),
  address       VARCHAR(240),
  city          VARCHAR(80),
  phone         VARCHAR(60),
  phone2        VARCHAR(60),
  email         VARCHAR(160),
  url           VARCHAR(240),
  region_id     SMALLINT REFERENCES regs.region,
  note          VARCHAR(400),
  sort_order    SMALLINT NOT NULL DEFAULT 0,
  record_status VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
                CHECK (record_status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  revision      INTEGER NOT NULL DEFAULT 1,
  updated_by    VARCHAR(120) NOT NULL DEFAULT 'system',
  updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_doc_id BIGINT REFERENCES regs.source_document,
  source_page   SMALLINT,
  CONSTRAINT uq_contact UNIQUE (season_year, contact_code)
);
CREATE INDEX ix_contact_year ON regs.contact (season_year, contact_kind, sort_order);

-- Immutable publish snapshot (public v2 reads ONLY this).
CREATE TABLE regs.published_contacts (
  season_year   SMALLINT NOT NULL,
  version       INTEGER  NOT NULL,
  contact_code  VARCHAR(60) NOT NULL,
  contact_kind  VARCHAR(20) NOT NULL,
  name          VARCHAR(160) NOT NULL,
  org           VARCHAR(160),
  address       VARCHAR(240),
  city          VARCHAR(80),
  phone         VARCHAR(60),
  phone2        VARCHAR(60),
  email         VARCHAR(160),
  url           VARCHAR(240),
  region_id     SMALLINT,
  note          VARCHAR(400),
  sort_order    SMALLINT NOT NULL,
  CONSTRAINT pk_published_contacts PRIMARY KEY (season_year, version, contact_code)
);

CREATE TRIGGER trg_audit_contact AFTER INSERT OR UPDATE OR DELETE ON regs.contact
  FOR EACH ROW EXECUTE FUNCTION regs.fn_audit_row('contact_id');

-- Down Migration
DROP TRIGGER IF EXISTS trg_audit_contact ON regs.contact;
DROP TABLE IF EXISTS regs.published_contacts;
DROP TABLE IF EXISTS regs.contact;
