#!/usr/bin/env bash
# @file gen-keystore.sh
# @module engage-mt/mobile/scripts
# @description Interactive Android release-keystore generator. Creates the
#              signing keystore + the gitignored keystore.properties that
#              release-android.sh / Gradle read. Never commits secrets and
#              verifies both are gitignored. Run ONCE per app, then back the
#              keystore up securely — losing it means you can never ship an
#              update to the same Play listing. / J-022.
# @author Jamie Ellis / Engage MT
# @created 2026-06-30
# @updated 2026-06-30
# @version 1.0.0
#
# FWP Engage MT — Montana's Official Gateway to the Outdoors
# Licensed under the MIT License.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(dirname "$SCRIPT_DIR")"

ALIAS="engagemt"
KEYSTORE_REL="app/engagemt.keystore"                       # relative to mobile/android (rootProject)
KEYSTORE_ABS="$MOBILE_DIR/android/$KEYSTORE_REL"
PROPS_ABS="$MOBILE_DIR/android/keystore.properties"

if ! command -v keytool >/dev/null 2>&1; then
  echo "❌ keytool not found (ships with the JDK)."
  echo "   Run: npm run mobile:bootstrap"
  exit 1
fi

echo "▶ Engage MT — Android release keystore generator"
echo ""
echo "  This creates:"
echo "    • $KEYSTORE_ABS   (the signing key — gitignored)"
echo "    • $PROPS_ABS   (passwords for Gradle — gitignored)"
echo ""

# --- refuse to clobber an existing keystore --------------------------------
if [ -f "$KEYSTORE_ABS" ]; then
  echo "⚠️  A keystore already exists at:"
  echo "    $KEYSTORE_ABS"
  echo "    Overwriting it would orphan any app already published with the old"
  echo "    key. Aborting. Delete it by hand only if you are certain."
  exit 1
fi

# --- collect passwords ------------------------------------------------------
read -r -s -p "  Choose a keystore password (min 6 chars): " STORE_PASS; echo ""
read -r -s -p "  Confirm keystore password: " STORE_PASS2; echo ""
if [ "$STORE_PASS" != "$STORE_PASS2" ] || [ ${#STORE_PASS} -lt 6 ]; then
  echo "❌ Passwords don't match or are too short."
  exit 1
fi
# Reuse the same password for the key (common + simplest); keytool allows it.
KEY_PASS="$STORE_PASS"

echo ""
echo "  Certificate identity (shown to no one; used inside the key). Press"
echo "  Enter to accept the FWP defaults."
read -r -p "    Organization [Montana Fish, Wildlife & Parks]: " ORG
ORG="${ORG:-Montana Fish, Wildlife & Parks}"
read -r -p "    City [Helena]: " CITY; CITY="${CITY:-Helena}"
read -r -p "    State [Montana]: " STATE; STATE="${STATE:-Montana}"
# Escape commas in each RDN value — keytool treats an unescaped `,` as an RDN
# separator, so an org like "Montana Fish, Wildlife & Parks" (the default!) fails
# with "Incorrect AVA format" unless the internal comma is `\,`-escaped.
esc_ava() { printf '%s' "$1" | sed 's/,/\\,/g'; }
DNAME="CN=Engage MT, O=$(esc_ava "$ORG"), L=$(esc_ava "$CITY"), ST=$(esc_ava "$STATE"), C=US"

# --- generate ---------------------------------------------------------------
echo ""
echo "▶ Generating RSA 2048 key (valid ~68 years)…"
keytool -genkeypair -v \
  -keystore "$KEYSTORE_ABS" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 2048 -validity 25000 \
  -storepass "$STORE_PASS" -keypass "$KEY_PASS" \
  -dname "$DNAME"

# --- write keystore.properties ---------------------------------------------
umask 077
cat > "$PROPS_ABS" <<EOF
# Generated by gen-keystore.sh — gitignored, NEVER commit.
storeFile=$KEYSTORE_REL
storePassword=$STORE_PASS
keyAlias=$ALIAS
keyPassword=$KEY_PASS
EOF
echo "  ✅ wrote $PROPS_ABS"

# --- verify gitignore -------------------------------------------------------
echo ""
echo "▶ Verifying both files are gitignored…"
gitignored_ok=1
for f in "$KEYSTORE_ABS" "$PROPS_ABS"; do
  if git -C "$MOBILE_DIR/.." check-ignore -q "$f"; then
    echo "  ✅ ignored: ${f#"$MOBILE_DIR/../"}"
  else
    echo "  ❌ NOT ignored: $f — add it to .gitignore before committing!"
    gitignored_ok=0
  fi
done

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  🔐 BACK UP THE KEYSTORE NOW — this is irreplaceable."
echo ""
echo "  Copy BOTH the keystore file and its passwords to a secure store"
echo "  (FWP password manager / secrets vault). If you lose this key you can"
echo "  NEVER publish an update to the same Google Play listing again."
echo "    keystore: $KEYSTORE_ABS"
echo "    alias:    $ALIAS"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "  Next: bash mobile/scripts/release-android.sh --apk   # signed APK"
echo "        bash mobile/scripts/release-android.sh         # signed AAB"

[ "$gitignored_ok" -eq 1 ]
