/**
 * @file loadPamphletContent.ts
 * @module engage-mt/server/etl
 * @description Hand-curated seed of the 2026 DEA book's prose sections that the Phase-B
 *              fees/content seed did not cover: FRONT_MATTER (director's letter, highlights,
 *              reminders, how-to-use, commission adoption, discrimination notice), CWD
 *              management (p.4), DEFINITIONS (glossary, acronyms, species ID), the LICENSING
 *              machinery (obtain / drawing / party / residency / license types / replacement /
 *              refunds / discounts / donations / nonresident info), DRAWING programs (SuperTag,
 *              preference points, landowner preference, drawing statistics, buy bonus points),
 *              YOUTH, DISABILITY, SAFETY (bear ID, bear country, lead), and ACCESS (hunter land
 *              access + general information). Faithful paraphrase preserving every MCA/ARM
 *              citation, dollar amount, date, and phone number verbatim — the same standard as
 *              the existing LAWS_RULES sections. Idempotent per (season_year, slug). Loads DRAFT.
 *              Usage: `tsx src/etl/loadPamphletContent.ts [year]` (default 2026).
 * @author Jamie Ellis / Engage MT
 * @created 2026-07-07
 * @updated 2026-07-07
 * @version 1.0.0
 *
 * FWP Engage MT — Montana's Official Gateway to the Outdoors
 * Licensed under the MIT License.
 */

import { withTransaction, closePool, query } from "../db/pool.js";

// slug, category, title, statute_refs|null, sort, source_page, body_md
type Section = [string, string, string, string | null, number, number, string];

const SECTIONS: Section[] = [
  // ══════════════ FRONT MATTER ══════════════
  ["directors-letter", "FRONT_MATTER", "Letter from the Director", null, 10, 6,
    "Last fall the Montana Fish and Wildlife Commission set the hunting regulations for 2026 and 2027, making changes to address concerns about nonresident hunting pressure and mule deer numbers.\n\nStarting in 2023 FWP began reducing deer B licenses in areas with declining mule deer numbers, and the legislature limited most nonresidents to one deer B license (or two with a combination license). This fall the commission **reduced the number of deer licenses a resident can hold from eight to three**, made some deer licenses valid only on private land within most of the state, and passed a **cap on the sale of a particular nonresident deer license** — cutting roughly 2,500 of those licenses available to nonresidents.\n\nBefore the next biennial season-setting process, FWP will finalize a new mule deer management plan shaped by public feedback. Report unethical or illegal behavior at tipmont.mt.gov, and refresh your hunting ethics at fwp.mt.gov/itsuptous.\n\n— Christy Clark, Director. *The **outside** is in us all.*"],
  ["highlights", "FRONT_MATTER", "Highlights", null, 20, 7,
    "- Resident deer hunters are limited to purchasing **three deer licenses** per license year (a general license and two B licenses, or three B licenses).\n- Many mule deer B licenses are now **restricted to private land only** — check the opportunity-specific details for each hunt.\n- Over-the-counter Deer B and Elk B license purchase date changed to **June 15**.\n- Hunting and fishing licenses are accessible through the secure Montana MyFWP app, which stores licenses and digital carcass tags (E-Tags) that validate your harvest in the field.\n- Photocopying or printing more than one license may constitute a violation; it is unlawful to apply for, purchase, or possess more licenses, permits, or tags than are authorized (see p.25).\n- Permits for either-sex elk or brow-tined bull-antlerless elk limit the holder to antlered elk within only the designated hunting district for the period on the permit; antlerless elk hunting is not limited by the permit.\n- Deadline for deer/elk permits and Nonresident Combination License applications is **April 1**.\n- Nonresidents hunting with a Montana-licensed outfitter applying for combination licenses may purchase an additional outfitter preference point at application.\n- To prevent the spread of CWD, follow the carcass disposal guidelines (see p.4)."],
  ["reminders", "FRONT_MATTER", "Reminders", null, 30, 7,
    "- Youth and Apprentice Hunter information — see p.19.\n- Game Damage Hunt Roster rules — see p.31.\n- License Discount Opportunities — see p.18.\n- Elk hunters can purchase multiple Elk B licenses — see p.16.\n- Landowners or their designees apply online or at an FWP office, then submit a separate landowner preference form. Preference forms for deer and elk permits must be received by **April 1**; forms for Elk B, Deer B, Antelope, and Antelope B must be received by **June 1**.\n- An email address is required of all applicants applying for limited licenses or permits."],
  ["how-to-use", "FRONT_MATTER", "How To Use These Regulations", null, 40, 7,
    "Montana's 147,164 square miles is divided into **seven administrative regions**, each with a main regional office. Each region is broken into hunting districts numbered to match the region: Region 1 districts start with 1 or 001, Region 2 with 2 or 002, and so on.\n\n**Before hunting you need to determine the following:**\n\n| Question | Deer / Elk | Antelope |\n|---|---|---|\n| **What** species do you want to hunt? | Deer / Elk | Antelope |\n| **Where** (find the hunting district) | Maps pp.32-43 | Maps pp.128-134 |\n| **When** can you hunt? | HD regs pp.48-123; youth & PTHFV p.124; multi-district pp.126-127; hunting hours p.151 | HD regs pp.136-142; hunting hours p.151 |\n| **How** do you want to hunt? | Archery (requires a Bow & Arrow License) or general weapon — see Laws & Rules p.23 and Weapons Restrictions p.28 | |\n| **Required** licenses/permits & deadlines | License and Permit Types pp.12-13; Residency p.14 | |\n| Know the legal **boundaries** | Restricted Area Descriptions pp.28-30 | |\n| **Complete** the drawing application by deadline | Find the 5-digit code pp.48-123 | Find the 5-digit code pp.136-142 |"],
  ["commission-adoption", "FRONT_MATTER", "Regulations Are Adopted by the Fish & Wildlife Commission", "MCA 87-1-301", 50, 8,
    "Regulations for season dates, structures, and restrictions were adopted by the Fish & Wildlife Commission on **December 4, 2025**, under the authority granted in MCA 87-1-301, and are **valid March 1, 2026 through February 28, 2027**. The Commission reserves the authority to amend the seasons, limits, and regulations herein if deemed necessary for wildlife management purposes. Statutes and other agencies' restrictions are provided as a courtesy and do not fall under Commission authority. — Christy Clark, Director."],
  ["discrimination-notice", "FRONT_MATTER", "Discrimination Prohibited", null, 60, 8,
    "State and Federal laws — Title VI of the Civil Rights Act of 1964, Section 504 of the Rehabilitation Act of 1973, Title II of the Americans with Disabilities Act of 1990, the Age Discrimination Act of 1975, and Title IX of the Education Amendments of 1972 — prohibit discrimination on the basis of race, color, sex, age, religion, national origin, or disability. Anyone who believes they have been discriminated against may write to FWP Human Resources, 1420 East Sixth Avenue, PO Box 200701, Helena, MT 59620-0701, or the Office of Diversity, Inclusion and Civil Rights, U.S. Department of the Interior, 1849 C Street NW, Washington, DC 20240."],

  // ══════════════ CWD ══════════════
  ["cwd-what-is", "CWD", "What Is Chronic Wasting Disease?", null, 10, 4,
    "CWD is a progressive, fatal neurological disease that affects deer, elk, and moose. There is no known case of CWD affecting people, pets, livestock, or wildlife other than the deer family. However, the World Health Organization and the Centers for Disease Control and Prevention (CDC) recommend not consuming meat from an animal known to be infected with CWD. The CDC also recommends that hunters have deer, elk, and moose tested if they were harvested in an area where CWD is known to be present, which includes hunting districts with, and adjacent to, those with CWD detections. Visit **fwp.mt.gov/cwd** for more information."],
  ["cwd-where", "CWD", "Where Is CWD?", null, 20, 4,
    "CWD has been detected across much of Montana. Maps of where CWD is found are updated regularly and can be found at fwp.mt.gov/conservation/chronic-wasting-disease/in-montana."],
  ["cwd-why-manage", "CWD", "Why Is CWD Management Important?", null, 30, 4,
    "Montana FWP has the responsibility for managing wildlife, which includes managing wildlife diseases. FWP's CWD management efforts:\n\n- Help prevent long-term population declines in infected herds. Some states have seen more than a **40% decline in mule deer**.\n- Decrease prevalence and likelihood of spread.\n- Help mitigate the disease's broader impacts to Montana's hunting and outdoor legacy."],
  ["cwd-dispose", "CWD", "Dispose, Don't Expose", null, 40, 4,
    "**Don't dump carcasses.** There are three reasons not to dump a game carcass:\n\n1. **It can spread CWD.** Once an animal with CWD dies, any part of the carcass can transmit the disease for at least two years.\n2. **It's illegal.** Montana State Law prohibits dumping dead animals or refuse on public property, including all state-owned and managed lands, FWP-managed fishing access sites, and wildlife management areas — risking a fine and loss of hunting and fishing privileges for a year.\n3. **It's unsightly.** A dumped carcass reflects poorly on the hunting community.\n\n**Follow carcass disposal guidelines.** To prevent the spread of CWD, all parts of the head or skull containing brain material and/or the spinal columns of deer, elk, and moose harvested in Montana must be left in the field at the kill site or, if transported for further processing (including taxidermy or meat processing), disposed of in a Class II landfill once that processing is complete."],

  // ══════════════ DEFINITIONS ══════════════
  ["definitions-glossary", "DEFINITIONS", "Definitions", "MCA 45-2-101, 87-2-101", 10, 8,
    "**General Deer/Elk Season:** typically five weeks long, mid-October through late-November; see hunting districts for specific dates by species.\n\n**Game Animal:** deer, elk, moose, antelope, caribou, mountain sheep, mountain goat, mountain lion, bear, and wild bison.\n\n**Hunt:** to pursue, shoot, wound, take, harvest, kill, chase, lure, possess, or capture, or the act of a person possessing a weapon (as defined in MCA 45-2-101) or using a dog or a bird of prey for the purpose of shooting, wounding, taking, harvesting, killing, possessing, or capturing wildlife.\n\n**Shoulder Season:** a hunting opportunity conducted before or after the five-week general deer/elk season; see individual hunting districts.\n\n**Migratory Game Bird / Upland Game Bird / Furbearer / Predatory Animal / Nongame Wildlife:** as classified by statute or rule.\n\n**License / Permit:** an electronic or hard-copy document issued to an individual granting, or to be used in conjunction with the proper license to grant, the opportunity to hunt the specific species of animal.\n\n**License Ambassador (formerly License Provider):** a third-party vendor offering self-service access to FWP's Online Licensing Service.\n\n**Outfitter / Guide:** as defined in statute; a guide is employed by or contracted independently with a licensed outfitter."],
  ["acronyms", "DEFINITIONS", "List of Acronyms", null, 20, 8,
    "| Acronym | Meaning |\n|---|---|\n| AISPP | Aquatic Invasive Species Prevention Pass |\n| ARM | Administrative Rules of Montana |\n| CR | Commission Rule |\n| CWD | Chronic Wasting Disease |\n| DNRC | Department of Natural Resources and Conservation |\n| F&W Commission | Fish and Wildlife Commission |\n| FAS | Fishing Access Site |\n| FWP | Fish, Wildlife & Parks |\n| HD | Hunting District |\n| HWY | Highway |\n| LPT | License or Permit Type |\n| MCA | Montana Code Annotated |\n| OTC | Over the Counter |\n| PTHFV | Permit to Hunt From a Vehicle |\n| PTMAE | Permit to Modify Archery Equipment |\n| WMA | Wildlife Management Area |\n| WPA | Waterfowl Production Area |\n| WRA | Weapons Restriction Area |"],
  ["species-id", "DEFINITIONS", "Identification Guide for Antelope, Deer & Elk", null, 30, 9,
    "**Antelope.** *Buck (Horned):* any antelope with a horn or horns at least 4 inches long as measured from the top of the skull (bucks have a distinctive black band under the lower jaw). *Doe/Fawn:* any antelope with horns less than 4 inches long.\n\n**Deer** (applies to both mule and white-tailed species). *Antlered Buck:* a deer with an antler or antlers at least 4 inches long as measured from the top of the skull. *Antlerless:* a deer without antlers, or with antlers less than 4 inches long. Caution: antlers on mule and white-tailed yearling bucks may look similar.\n\n**Elk.** *Antlered Bull:* any elk having an antler or antlers at least 4 inches long. *Antlerless:* a female or juvenile male with antlers less than 4 inches long. *Brow-tined:* any elk having an antler or antlers with a visible point on the lower half of either main beam greater than or equal to 4 inches long. *Spike Bull:* any elk having antlers that do not branch or, if branched, branch less than 4 inches long measured from the main antler beam. *Either-sex:* a male or female animal of any age."],

  // ══════════════ LICENSING ══════════════
  ["obtain-license", "LICENSING", "Obtain a License or Permit", "MCA 87-2-104, 87-2-704, ARM 12.3.601", 100, 14,
    "Only one license or permit of any type may be purchased each year unless otherwise specified (for example, a hunter may purchase more than one elk B license). Many licenses and permits may be purchased from FWP license ambassadors, FWP offices, or online licensing; some are available only through a drawing. Refer to the Licenses Available Chart (pp.12-13) for the full resident and nonresident list and application deadlines.\n\n**Online licensing:** apply for and purchase many licenses at **ols.fwp.mt.gov**, generally between 5:00 a.m. and 11:45 p.m. Montana time. Montana residents can purchase resident licenses online or at a license ambassador with a valid Montana driver's license issued at least six months prior. All license purchases and applications are final and cannot be changed if drawn (ARM 12.3.601)."],
  ["drawing-applications", "LICENSING", "Drawing Applications", null, 101, 14,
    "All applications for deer and elk permits must be submitted on or before **April 1**. Antelope, antelope B, deer B, and elk B applications must be submitted on or before **June 1**. Both resident and nonresident hunters are eligible to apply for most licenses awarded through the drawings. Drawings are based on the final quotas adopted by the F&W Commission, which may differ from those printed in these regulations. An email address is required of all applicants for limited licenses or permits."],
  ["party-applications", "LICENSING", "Party Applications", null, 102, 14,
    "In Montana a \"party\" means a group of **2-5 persons** applying together to obtain a license or permit. If successful, each hunter must harvest their own game. All party members must select the same opportunity type and the same bonus- or preference-point participation. For online applications, the party establisher lists all members and provides the party number to each; each member then applies online using that number. Bonus/preference points for party applications are the average of the members' individual points."],
  ["residency", "LICENSING", "Residency", "MCA 87-2-102, 87-2-105", 103, 14,
    "To be a lawful Montana resident eligible to purchase resident fishing, hunting, and trapping licenses, you must: have been physically living in Montana for at least **180 consecutive days** immediately prior to purchasing a resident license; register your vehicle(s) in Montana; be registered to vote in Montana if registered to vote at all; not possess or have applied for any current resident hunting/fishing/trapping privilege in another state or country; and file Montana resident income tax returns if required to file. Once established, you must continue to meet all of these requirements and physically reside in Montana as your principal or primary place of abode for not less than **120 days** per year (days need not be consecutive). A person is not a resident if they claim residency in another state or country for any purpose, or are an absentee property owner paying property tax in Montana. An out-of-state driver's license is not acceptable ID for resident license purchases (MCA 87-2-105/87-2-106)."],
  ["nonresident", "LICENSING", "Nonresident", "MCA 87-2-506", 104, 14,
    "A nonresident is eligible to purchase or apply for most Montana fishing, hunting, and trapping licenses. By state law, nonresidents are limited to, but not guaranteed, **10 percent** of the license and/or permit quota for a district. A nonresident unmarried minor, at least 12 (by Jan. 16, 2027) but not older than 17, may hunt and fish in Montana as a resident if the minor's parent, legal guardian, or parent with joint custody, sole custody, or visitation rights is a resident of Montana (see the Youth Hunter chart)."],
  ["armed-forces", "LICENSING", "Armed Forces", "MCA 87-2-102", 105, 14,
    "A member of the regular armed forces of the United States, a member's spouse or dependent (as defined in 10-30-2115) who resides in the member's household, or a dependent who is a member of the armed forces of a foreign government attached to the regular armed forces of the United States, is considered a resident for Montana hunting, fishing, and trapping licenses."],
  ["license-types-deer", "LICENSING", "Deer Licenses & Permits", null, 110, 15,
    "**General Deer License** — valid for one deer as indicated under the \"General Deer License\" heading on the hunting-district pages. Hunters may hold only one General Deer License; residents may buy a Sportsman's License, which includes one. Most nonresidents cannot buy a general deer license over the counter and must obtain one through a Big Game Combination, Deer Combination, or Landowner-Sponsored drawing.\n\n**Deer Permit** — allows hunting in an otherwise restricted area or time period; must be used with a General Deer License. Residents must hold a General Deer License before applying; nonresidents must hold or apply for a Big Game or Deer Combination License.\n\n**Deer B License** — usually for antlerless mule deer or white-tailed deer depending on the license type and hunting district, and allows harvest of a deer in addition to the general deer. **Resident deer hunters are limited to three deer licenses per year, only one of which may be a General Deer License.**"],
  ["license-types-elk", "LICENSING", "Elk Licenses & Permits", null, 111, 16,
    "**General Elk License** — valid for one elk. Hunters may hold only one. Most nonresidents obtain a General Elk License through a Big Game or Elk Combination drawing.\n\n**Elk B License** — valid for taking an antlerless elk during a specific period in a particular district or group of districts; designed to control elk numbers and many are valid only on private land. Limited elk B licenses are drawn (deadline June 1); unlimited (UNL) elk B licenses have no sales limit and are available OTC. The only prerequisites are a Conservation License and Base Hunting License. **A hunter may possess a total of three elk licenses in a year, only one of which can be a General Elk License.**"],
  ["license-types-antelope", "LICENSING", "Antelope Licenses & Permits", "MCA 87-2-506", 112, 15,
    "**Antelope License (either-sex)** — the total number of antelope licenses an individual may hold is limited to one, of which only one may be either-sex. Both residents and nonresidents may apply through the drawings; nonresidents are limited to 10 percent of the quota.\n\n**Antelope B License (doe/fawn)** — the cost of the first nonresident antelope B license (through the drawing, over-the-counter, or surplus) is $200; additional nonresident antelope B licenses cost $150.\n\n**Antelope Archery Only License (900/399, drawing only)** — valid for either-sex antelope with archery equipment only. Applicants must list the 900-20 (or 399-20) license as their **first and only choice**. Region 3 has a separate archery-only license."],
  ["replacing-license", "LICENSING", "Replacing a Lost License", "MCA 87-2-1304", 113, 16,
    "Replacements of lost, stolen, or destroyed licenses or permits may be purchased online, at FWP offices, or from license ambassadors for a **$5 fee** per replacement license. The department will issue a replacement license when an animal is deemed unfit for human consumption due to disease or prior injury: the person must surrender the entire animal, may choose the same or the next license year, and must appear in person at an FWP regional office or headquarters in Helena during normal operating hours. Contact Licensing at 406-444-2950 or fwpgen@mt.gov."],
  ["fees-and-refunds", "LICENSING", "Fees and Refunds", null, 114, 18,
    "In addition to the cost of each permit or license, there is a **$5 nonrefundable application fee** for each license or permit you apply for. Prerequisite licenses (Conservation License, Base Hunting License, and AISPP) are also nonrefundable.\n\nFWP may issue an **80% refund** for a Nonresident Combination License obtained through a drawing if returned prior to **August 1** and the start of the archery or general season; a **50% refund** is issued between August 1 and the start of the general season if the license has not been used. Nonresident license holders should call 406-444-2950. Other refunds require appropriate documentation:\n\n| Reason | Deadline | Refund |\n|---|---|---|\n| Death of licensee | 12/1/26 | 100% |\n| Death of immediate family member | 12/1/26 | 90% |\n| Medical emergency | 12/1/26 | 90% |"],
  ["license-discounts", "LICENSING", "License Discount Opportunities", "MCA 87-2-817", 115, 18,
    "Montana resident members of the Montana National Guard, Federal Reserve, or Active Duty who participated after September 11, 2001, in a contingency operation outside the state for two months and have been released from active duty or discharged are entitled to a free Conservation License and a Fishing License. Youth, senior, and disabled discounts are shown on the Licenses Available Chart (pp.12-13)."],
  ["combat-disabled-veterans", "LICENSING", "Certain Combat Disabled Veterans", "MCA 87-2-817", 116, 20,
    "A veteran with certain combat-connected injuries may be entitled to half-priced licenses for deer and antelope. Up to **50 licenses** will be issued annually. Contact FWP Licensing for details at 406-444-2950."],
  ["donation-options", "LICENSING", "Donation Options", null, 120, 11,
    "When purchasing licenses you may donate to several programs:\n\n- **Wolf Mitigation** — funds the Montana Department of Livestock's contracts with USDA Wildlife Services for wolf management (flight time, collaring, lethal control).\n- **Warm Water Fisheries Enhancement** — supports projects that improve Montana's warm water fisheries and habitats.\n- **Hunters Against Hunger** — covers processing and distribution of donated meat to feed hungry Montanans (mfbn.org/hunters-against-hunger).\n- **MT-PLAN** — a DNRC grant program enhancing public access.\n- **Bowhunters with Disabilities Program** — covers the cost of modified archery equipment for disabled hunters."],
  ["nonresident-info", "LICENSING", "Nonresident Hunter Information", "MCA 87-2-115, 87-2-506", 130, 46,
    "Montana law governs nonresident hunters differently than residents:\n\n- All nonresidents are limited to, but not guaranteed, **10% of the overall drawing quota** for an opportunity (a district with 100 permits allows nonresidents to draw only 10).\n- The 10% cap includes both nonresident landowners and regular nonresidents; landowner preference is the first stage of the drawing and can account for up to 15% of total quotas.\n- Nonresidents must be successful in the **nonresident combination drawing** before moving on to specific permit drawings. Combination licenses are drawn by preference points: applicants with the most preference points are drawn first, but Montana law reserves **25% of nonresident combination licenses for applicants with zero preference points** (MCA 87-2-115).\n\n*Drawing-status meanings:* \"**Released**\" — initially unsuccessful in the primary phase but later successful from returned licenses. \"**Unsuccessful**\" with a zero preference-point balance — successfully drew a combination license in the primary drawing but elected to return it (which resets preference points to zero)."],

  // ══════════════ DRAWING ══════════════
  ["supertag", "DRAWING", "SuperTag Lottery", "MCA 87-1-271", 200, 16,
    "Open to residents and nonresidents. Chances are sold electronically at all FWP license ambassadors and via ols.fwp.mt.gov for **$5 each**, for a chance at a hunting license for deer, elk, antelope, bighorn sheep, moose, mountain goat, and mountain lion. Each SuperTag license allows the winner to hunt in any Montana hunting district valid for that species, even if the district quota has been met. An individual may win one or a combination of SuperTags per year. Proceeds enhance public hunting access and FWP enforcement. Montana residents receive one free chance in a separate resident lottery for every General Elk or General Deer License purchased."],
  ["preference-points", "DRAWING", "Preference Points", "MCA 87-2-115", 210, 18,
    "**75%** of Nonresident Combination Licenses are awarded to applicants in order of the greatest number of preference points; the other **25%** are awarded to applicants who hold no preference points, drawn at random. You do not have to apply to accumulate a preference point — select \"YES\" on the preference-point question and a **$100 fee** is added. All accumulated preference points, including one purchased at application, are used in the current drawing. Preference points are not reinstated if you successfully draw and then refund your Nonresident Combination License. **No one may hold more than three preference points.** A person who does not apply for a combination license may purchase one preference point for $100 between July 1 and Dec 31."],
  ["landowner-preference", "DRAWING", "Landowner Preference", "MCA 87-2-705", 220, 17,
    "Montana landowners (resident and nonresident) may qualify for preference in the license/permit drawings for deer, elk, and antelope. Up to **15 percent** of final quotas may be set aside for landowner-preference applicants. Landowners or their designees apply by the applicable deadline and submit a separate landowner preference form: forms for **deer and elk permits** must be received by **April 1**, and forms for **Elk B, Deer B, Antelope, and Antelope B** must be received by **June 1**. A landowner must be eligible to hunt in the hunting district applied for."],
  ["drawing-statistics", "DRAWING", "Drawing Statistics & Bonus Points", "MCA 87-2-117", 230, 45,
    "After each drawing, FWP publishes drawing statistics online showing the number of applicants in each category (resident landowner, nonresident landowner, resident, nonresident), the final quotas, and the number of successful applicants per opportunity, plus a detailed bonus-point report. **The quotas printed in these regulations may vary from the final quotas drawn based on biological surveys.** See fwp.mt.gov/buyandapply/hunting-licenses/drawing-statistics.\n\n**How bonus points work:** every applicant gets one chance in the drawing; bonus points add \"raffle tickets.\" Montana **squares** bonus points before the drawing, so chances grow exponentially. With 10 bonus points you get 101 chances — 100 for the squared points and 1 for the current application: (10 × 10) + 1 = 101. The system is designed to be completely random."],
  ["buy-bonus-points", "DRAWING", "Buy Bonus Points", "MCA 87-2-117", 240, 45,
    "In years you don't apply for a license, a bonus point can be purchased separately **between July 1 and Sept 30** to increase your chances for a future license or permit. Deer, elk, and antelope bonus points cost $20 (resident) / $25 (nonresident) per species. See fwp.mt.gov/buyandapply/hunting-licenses/bonus-points."],

  // ══════════════ YOUTH ══════════════
  ["youth-hunter", "YOUTH", "Youth Hunter", null, 300, 19,
    "**Special 2-day Youth Deer Hunt: October 15 & 16, 2026.** Lawfully licensed hunters **10 through 15 years of age** may hunt deer statewide during these two days with a general deer, deer permit, or deer B license, taking the deer species otherwise available on that license in the district being hunted. An adult at least 18 years of age must accompany the youth in the field. Shooting hours, hunter education requirements, and all other general-season regulations apply.\n\nSome hunting districts offer additional special opportunities for youth ages 10-15 (see the district regulations and p.124). Youth who are 15 at the start of the general season may hunt in the youth areas with a general license even if they turn 16 during the season."],
  ["apprentice-hunter", "YOUTH", "Apprentice Hunter", null, 310, 19,
    "An apprentice hunter is a resident or nonresident certified at an FWP office or online. A person can certify as early as age 9 but cannot use a license until age 10. The certification lets the apprentice hunt some species while accompanied by a mentor without first completing a hunter education course, and is limited to **two years** before hunter education is required. An apprentice may not apply for or purchase a bighorn sheep, moose, mountain goat, mountain lion, or wolf license, or a hunting license/permit with a limited quota. See fwp.mt.gov/hunt/education/apprentice-hunter."],
  ["youth-elk-permits", "YOUTH", "Youth Elk Permits and Elk B Licenses", null, 320, 19,
    "Elk permits and Elk B Licenses issued only to youth **12 (by Jan 16, 2027) through 15 years of age** require the applicant to be within that age range at the time of application and to show proof of successfully completing hunter education. A youth 11 years of age who will reach 12 by Jan. 16, 2027, may apply for any special drawing after completing an approved hunter education course, and after Aug. 15, 2026, may hunt any game species for which their license is valid during an open season. In order to carry or use a firearm in public, a youth under 14 must be accompanied by a person having charge or custody of the child or under supervision as provided in MCA 45-8-344."],
  ["terminally-ill-youth", "YOUTH", "Free Licenses for Terminally Ill Youth", "MCA 87-2-805", 330, 19,
    "Montana law allows a terminally ill resident or nonresident youth under 18 years of age to receive a free one-time Deer and Elk Combination license (without bear), or a deer, elk, or antelope license/permit as applicable. The youth must be accompanied by a licensed outfitter or an adult licensed to hunt in Montana. Minimum age and hunter education requirements may be waived. For information, call Licensing at 406-444-2950."],
  ["nonresident-youth-combo", "YOUTH", "Nonresident Youth Combination License", null, 340, 19,
    "Nonresident Youth Combination Licenses are sold to nonresident youth (ages 12-17) who have an adult immediate-family sponsor — a natural or adoptive parent, stepparent, grandparent, brother, or sister at least 18 years of age who possesses a current resident or nonresident deer or elk license. The youth must be accompanied by the sponsor while hunting. For details and an application, contact Licensing at 406-444-2950."],

  // ══════════════ DISABILITY ══════════════
  ["pthfv", "DISABILITY", "Permit to Hunt From a Vehicle (PTHFV)", "MCA 87-2-803", 400, 20,
    "Residents and nonresidents certified as permanently and substantially nonambulatory (as defined by state law) may apply for a Permit to Hunt From a Vehicle. Specific PTHFV field regulations apply. Applicants must apply on FWP-provided forms available at FWP offices or the FWP website; for more information contact FWP Licensing at 406-444-2950."],
  ["ptmae", "DISABILITY", "Permit to Modify Archery Equipment (PTMAE)", null, 410, 20,
    "Residents and nonresidents certified as permanently and substantially disabled (as defined by FWP rules) may apply for a Permit to Modify Archery Equipment. The PTMAE allows a person with a disability to use archery tackle that supports the bow and draws, holds, and releases the arrow to accommodate the individual's disability. Arrows are not exempt and must meet the requirements for the Archery Only Season. This permit does not entitle the holder to use a crossbow during the Archery Only Season."],
  ["disabled-conservation", "DISABILITY", "Resident With a Disability Conservation License", "MCA 87-2-803", 420, 20,
    "Residents certified as permanently and substantially disabled (as defined by FWP rules) who purchase a conservation license may also purchase a fishing license for half price (AISPP also required), and may purchase general deer, general elk, and/or upland bird licenses for half price. Applications are available at all FWP offices and the FWP website. The certification is valid for the life of the holder or until changed by the Montana Legislature."],
  ["disabled-antelope", "DISABILITY", "Antelope License for Hunters with a Disability", "ARM 12.3.106", 430, 20,
    "Individuals who are permanently physically disabled and nonambulatory (as defined in ARM 12.3.106) may apply for an antelope license. A total of **25 antelope licenses** are issued through the antelope drawing, offered in antelope hunting districts that have a total quota of 50 or more antelope licenses. Applicants must apply on FWP-provided forms at any FWP office; applications must be postmarked on or before **June 1**."],

  // ══════════════ SAFETY ══════════════
  ["bear-identification", "SAFETY", "Bear Identification — Grizzly vs. Black Bear", null, 500, 47,
    "Black bear hunters must be able to tell the difference between a grizzly and a black bear, because **grizzly bears cannot be legally hunted in Montana**.\n\n| | Grizzly Bear | Black Bear |\n|---|---|---|\n| Shoulder | Prominent shoulder hump | No shoulder hump |\n| Face profile | Dished | Straight |\n| Ears | Shorter, rounded | Pointed, tall |\n| Claws | Long, 2\"-4\" | Short, ~0.5\" |\n| Tracks | Longer claws, toes closer together | Shorter claws, toes more separated |\n\nColor and size can be misleading — look for a combination of characteristics. **If in doubt, don't shoot.** Learn how to identify bears and be absolutely sure of your target."],
  ["bear-country", "SAFETY", "How to Hunt Safely in Bear Country", null, 510, 47,
    "Minimize the likelihood of encountering a bear — calling game and using scents may attract bears, and camps, cabins, and horses should be kept bear-proof with attractants minimized. Carry **bear spray** at the ready in an accessible holster and know how to use it; in sudden grizzly encounters bear spray has proven effective. Report encounters where a grizzly displayed aggressive or defensive behavior toward people, livestock, or pets to FWP at **1-800-TIP-MONT**, the U.S. Forest Service, or the nearest FWP bear management specialist (listed on the printed Bear Aware page). Simply seeing a grizzly is not necessarily a reportable encounter. In an actual emergency, phone **9-1-1**."],
  ["lead-facts", "SAFETY", "Know the Facts About Lead", null, 520, 144,
    "Lead particles from lead ammunition can be toxic if ingested and can poison wildlife scavenging from gut piles. Hunters can voluntarily choose to use non-lead, copper, or other high-weight-retention ammunition. To learn more, visit NonleadPartnership.org or HuntingWithNonLead.org. *FWP cannot regulate ammunition according to Montana statute; the law does not prohibit the use of lead ammunition.*"],

  // ══════════════ ACCESS ══════════════
  ["hunter-land-access", "ACCESS", "Hunter Land Access", null, 600, 31,
    "**Private land** — Montana law requires permission for all hunting on private land, regardless of whether the land is posted. See FWP's Block Management Program (contact FWP at 406-444-3750); FWP publishes a Hunting Access Guide by Aug. 15 each year.\n\n**Public land** — National Parks and National Park Service areas are closed to hunting. National Forests, National Wildlife Refuges, U.S. Forest Service, and BLM lands may have restrictions and closures; inquire at the local federal office. It is unlawful to post, place signs, or mark state or federal land other than by the managing agency.\n\n**Railroads** — railroad right-of-ways are private property and may not be hunted or used for access without explicit permission.\n\n**State School Trust Lands** — a Conservation License provides hunters, anglers, and trappers access to lawfully accessible State School Trust Lands during applicable seasons; additional requirements apply (DNRC 406-444-2074). Motorized travel is restricted to designated roads/trails; firearms may not be discharged within 1/4 mile of inhabited dwellings without permission.\n\n**Stream Access Law** — does not allow hunting of game animals between the ordinary high-water marks of streams and rivers without landowner permission.\n\n**State Parks** — some provide hunting; restrictions may apply (stateparks.mt.gov).\n\n**Indian Reservation Trust Lands** — some reservations may offer opportunities with a tribal license; contact the appropriate tribal government (see Contacts, p.144)."],
  ["game-damage-roster", "ACCESS", "Game Damage Hunt Roster Rules", null, 610, 31,
    "The game damage hunt roster is a randomized list of hunters' names. If FWP identifies a need to implement a game damage hunt, roster hunters will be contacted by FWP. Sign-up for the game damage hunt roster is from **June 15-July 15, 2026**, and only on the FWP website through MyFWP."],
  ["donate-license-veteran", "ACCESS", "Donate a Hunting License to a Disabled Veteran", "MCA 87-2-855", 620, 31,
    "Residents and nonresidents can donate their Montana hunting license to a disabled military veteran or disabled active-duty service member working with an organization that uses hunting as part of the rehabilitation process. The recipient must be a Purple Heart recipient with a 70 percent or greater disability rating. Visit the FWP website for more information."],
  ["weed-seed-free", "ACCESS", "Weed Control and Weed-Seed-Free Feed", null, 630, 31,
    "Montana requires the use of certified weed-seed-free hay, grain, straw, mulch, cubes, and pelletized feed on state and federal lands. For more information, contact the Montana Department of Agriculture at 406-444-3144."],
  ["twelve-hour-closure", "ACCESS", "12-Hour Closure (Region 4 elk HD 424 & 442)", null, 640, 31,
    "In Administrative Region 4, elk hunting districts **424 and 442** may be subject to a 12-hour closure for the antlerless portion of the general season. If the antlerless quota is reached, the general season reverts to only the brow-tined bull regulation until the end of the general season. Contact Region 4 Headquarters or the Augusta Check Station for updates at 406-562-3467."],
];

export async function loadPamphletContent(seasonYear = Number(process.argv[2]) || 2026): Promise<void> {
  const sd = await query<{ v: string }>(`SELECT source_doc_id::text AS v FROM regs.source_document WHERE season_year=$1 LIMIT 1`, [seasonYear]);
  const sourceDocId = sd.rows[0]?.v ?? null;

  await withTransaction("etl-pamphlet-content", async (c) => {
    for (const [slug, cat, title, refs, sort, page, body] of SECTIONS) {
      const existing = await c.query<{ id: string }>(`SELECT section_id AS id FROM regs.content_section WHERE season_year=$1 AND slug=$2`, [seasonYear, slug]);
      if (existing.rows[0]) {
        await c.query(`UPDATE regs.content_section SET category=$3, title=$4, body_md=$5, statute_refs=$6, sort_order=$7, updated_by='etl' WHERE season_year=$1 AND slug=$2`,
          [seasonYear, slug, cat, title, body, refs, sort]);
      } else {
        await c.query(`INSERT INTO regs.content_section (season_year, slug, category, title, body_md, statute_refs, sort_order, updated_by, source_doc_id, source_page)
                       VALUES ($1,$2,$3,$4,$5,$6,$7,'etl',$8,$9)`, [seasonYear, slug, cat, title, body, refs, sort, sourceDocId, page]);
      }
    }
  });
  const cs = await query<{ n: string }>(`SELECT count(*) AS n FROM regs.content_section WHERE season_year=$1`, [seasonYear]);
  console.log(`Pamphlet content for ${seasonYear}: ${SECTIONS.length} sections upserted (${cs.rows[0]!.n} content sections total, DRAFT).`);
}

const isMain = process.argv[1]?.endsWith("loadPamphletContent.ts") || process.argv[1]?.endsWith("loadPamphletContent.js");
if (isMain) {
  loadPamphletContent().then(() => closePool()).then(() => process.exit(0)).catch((e) => { console.error(e); void closePool().finally(() => process.exit(1)); });
}
